# Generated by Django 5.1.3 on 2024-11-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_temp", models.FloatField(default=25.0)),
                ("fan_speed", models.IntegerField(default=1)),
                ("service_time", models.FloatField(default=0)),
                ("is_on", models.BooleanField(default=False)),
                ("current_temp", models.FloatField(default=25.0)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.IntegerField(unique=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=10)),
                ("target_temp", models.FloatField(null=True)),
                ("fan_speed", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetailedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("mode", models.CharField(max_length=20)),
                ("target_temp", models.FloatField()),
                ("fan_speed", models.IntegerField()),
                ("rate", models.FloatField()),
                ("fee", models.FloatField()),
                (
                    "air_conditioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UsingAC.airconditioner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_fee", models.FloatField()),
                ("check_in", models.DateTimeField(auto_now_add=True)),
                ("check_out", models.DateTimeField(null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UsingAC.room"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="airconditioner",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="UsingAC.room"
            ),
        ),
        migrations.CreateModel(
            name="ServiceObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fan_speed", models.IntegerField()),
                ("target_temp", models.FloatField()),
                ("service_time", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UsingAC.room"
                    ),
                ),
            ],
        ),
    ]
