# Generated by Django 5.1.3 on 2024-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsingAC", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airconditioner",
            name="AC_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="detailedlist",
            name="room",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="ServiceObject",
        ),
    ]
