# Generated by Django 5.1.3 on 2024-11-30 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UsingAC", "0002_airconditioner_ac_id_detailedlist_room_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedlist",
            name="air_conditioner",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="room",
        ),
        migrations.DeleteModel(
            name="AirConditioner",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
    ]
